export const companionData = [
  "Nguyễn Ngọc Thịnh",
  "Phan Đức Duy",
  "Phạm Phúc Thành Công",
  "Lê Thanh Huy",
  "Nguyễn Quốc Mạnh",
  "Phạm Văn Quân",
  "Nguyễn Văn Hết",
  "Trần Công Ngọ",
  "Nguyễn Bá Nhật Tài",
  "Phạm Thị Kiều Trinh",
  "Phạm Thị Kiều Oanh",
  "Phạm Thị Kiều Hân",
  "Phạm Thị Kiều Xuân",
  "Phạm Thị Kiều Mai",
];
